  # 站点信息
  site_name: Fedi 新手用户指南
  site_url: https://fedi-wiki.tkg3.top
  site_description: 一个面向新手用户的fediverse指南。
  copyright: ©2025 Circlari-team and all contributers

  # 自定义
  theme:
    name: material
    language: zh
    features:
      - navigation.top
      - navigation.tabs  
      - navigation.sections  
      - navigation.expand 
      - navigation.instant
      - toc.integrate  
      - search.suggest  
      - search.highlight  
      - content.code.copy  
      - content.code.annotate
    palette:
      - scheme: default 
        primary: indigo
        accent: pink
        toggle:
          icon: material/weather-sunny
          name: 切换到夜间模式 
      - scheme: slate
        primary: black
        accent: pink
        toggle:
          icon: material/weather-night
          name: 切换到日间模式

  # 仓库信息
  repo_url: https://github.com/Circlari/fedi-user-wiki
  repo_name: fedi-user-wiki 

  # Markdown 扩展
  markdown_extensions:
    - admonition
    - pymdownx.details
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight: 
        anchor_linenums: true
        line_spans: __span 
        pygments_style: monokai
    - pymdownx.inlinehilite 
    - pymdownx.tabbed:  
        alternate_style: true 
    - toc:
        permalink: true

  # MkDocs 插件
  plugins:
  - search
  - git-revision-date-localized:
      enabled: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true

  # 文档结构
  nav:
    - 首页: 
      - 欢迎: index.md
      - 内容贡献指南: contribute-guide.md
    - 联邦宇宙:
      - 概念: fediverse/intro.md
    - Mastodon:
      - 简介: mastodon/intro.md
    - Misskey:
      - 简介: misskey/intro.md

